"""add installation identity

Revision ID: 533f553dfaec
Revises: 8190aa0c4905
Create Date: 2026-08-07 04:43:37.729274+00:00

Data impact:
Rollback:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "533f553dfaec"
down_revision: str | None = "8190aa0c4905"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("installation_id", sa.String(length=40), nullable=False),
        sa.Column(
            "installed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("installed_version", sa.String(length=40), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_installation_single_row"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("installation")
    # ### end Alembic commands ###
