"""add send accounting column

Revision ID: 7909a5b29a0c
Revises: 533f553dfaec
Create Date: 2026-08-07 05:57:13.839538+00:00

Data impact:
Rollback:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7909a5b29a0c'
down_revision: str | None = '533f553dfaec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_messages_rate_window', 'messages', ['mailbox_id', 'last_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_rate_window', table_name='messages')
    op.drop_column('messages', 'last_attempt_at')
    # ### end Alembic commands ###
