"""initial schema

Revision ID: 8190aa0c4905
Revises:
Create Date: 2026-08-07 04:18:48.220070+00:00

Data impact:
Rollback:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8190aa0c4905"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "added",
                "ownership_pending",
                "dns_incomplete",
                "verified",
                "ready",
                "suspended",
                "misconfigured",
                name="domain_status",
            ),
            server_default=sa.text("'added'"),
            nullable=False,
        ),
        sa.Column("smtp_host", sa.String(length=253), nullable=True),
        sa.Column("dns_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dns_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_token", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "suppressions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "bounce", "complaint", name="suppression_source"),
            server_default=sa.text("'manual'"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index("ix_suppressions_address", "suppressions", ["address"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index("ix_api_keys_hash_active", "api_keys", ["key_hash", "active"], unique=False)
    op.create_table(
        "mailboxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=320), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("hourly_limit", sa.Integer(), server_default=sa.text("400"), nullable=False),
        sa.Column("daily_limit", sa.Integer(), server_default=sa.text("9600"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("provisioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "daily_limit > 0 AND daily_limit <= 9600", name="ck_mailbox_daily_limit"
        ),
        sa.CheckConstraint(
            "hourly_limit > 0 AND hourly_limit <= 400", name="ck_mailbox_hourly_limit"
        ),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
    )
    op.create_index("ix_mailboxes_domain", "mailboxes", ["domain_id"], unique=False)
    op.create_table(
        "api_key_scopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("mailbox_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mailbox_id"], ["mailboxes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_id", "mailbox_id", name="uq_scope_key_mailbox"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("mailbox_id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "sending",
                "accepted_by_provider",
                "temporarily_failed",
                "permanently_rejected",
                "canceled",
                name="message_status",
            ),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column("from_address", sa.String(length=320), nullable=False),
        sa.Column("from_name", sa.String(length=200), nullable=True),
        sa.Column("to_addresses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cc_addresses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("bcc_addresses", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reply_to", sa.String(length=320), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("return_path", sa.String(length=320), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("size_bytes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("recipient_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=100), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_response", sa.Text(), nullable=True),
        sa.Column(
            "failure_class",
            sa.Enum(
                "auth_failure",
                "recipient_rejected",
                "sender_unauthorized",
                "sender_mismatch",
                "rate_limited",
                "provider_deferral",
                "connection",
                "policy_rejected",
                "message_invalid",
                "internal",
                "unknown",
                name="failure_class",
            ),
            nullable=True,
        ),
        sa.Column("failure_code", sa.Integer(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["mailbox_id"], ["mailboxes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_messages_body_purge",
        "messages",
        ["completed_at"],
        unique=False,
        postgresql_where="body_purged_at IS NULL AND completed_at IS NOT NULL",
    )
    op.create_index(
        "ix_messages_needs_review",
        "messages",
        ["needs_review"],
        unique=False,
        postgresql_where="needs_review",
    )
    op.create_index(
        "ix_messages_project_created", "messages", ["project_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_messages_queue_claim",
        "messages",
        ["next_attempt_at"],
        unique=False,
        postgresql_where="status IN ('queued', 'temporarily_failed')",
    )
    op.create_index(
        "ix_messages_stale_claims",
        "messages",
        ["claimed_at"],
        unique=False,
        postgresql_where="status = 'sending'",
    )
    op.create_table(
        "send_counters",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mailbox_id", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("provider_sent_today", sa.Integer(), nullable=True),
        sa.Column("provider_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("drift_ratio", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["mailbox_id"], ["mailboxes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mailbox_id", "window_start", name="uq_counter_mailbox_window"),
    )
    op.create_index(
        "ix_send_counters_lookup", "send_counters", ["mailbox_id", "window_start"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "sequence", name="uq_event_message_sequence"),
    )
    op.create_index("ix_events_message", "events", ["message_id", "sequence"], unique=False)
    op.create_index("ix_events_type_time", "events", ["event_type", "occurred_at"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key", name="uq_idempotency_project_key"),
    )
    op.create_index("ix_idempotency_expires", "idempotency_keys", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_idempotency_expires", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_events_type_time", table_name="events")
    op.drop_index("ix_events_message", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_send_counters_lookup", table_name="send_counters")
    op.drop_table("send_counters")
    op.drop_index(
        "ix_messages_stale_claims", table_name="messages", postgresql_where="status = 'sending'"
    )
    op.drop_index(
        "ix_messages_queue_claim",
        table_name="messages",
        postgresql_where="status IN ('queued', 'temporarily_failed')",
    )
    op.drop_index("ix_messages_project_created", table_name="messages")
    op.drop_index(
        "ix_messages_needs_review", table_name="messages", postgresql_where="needs_review"
    )
    op.drop_index(
        "ix_messages_body_purge",
        table_name="messages",
        postgresql_where="body_purged_at IS NULL AND completed_at IS NOT NULL",
    )
    op.drop_table("messages")
    op.drop_table("api_key_scopes")
    op.drop_index("ix_mailboxes_domain", table_name="mailboxes")
    op.drop_table("mailboxes")
    op.drop_index("ix_api_keys_hash_active", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("ix_suppressions_address", table_name="suppressions")
    op.drop_table("suppressions")
    op.drop_table("projects")
    op.drop_table("domains")
    # ### end Alembic commands ###
