"""observability: heartbeats and latency

Revision ID: f53f35ee9839
Revises: 7909a5b29a0c
Create Date: 2026-08-07 13:06:22.814270+00:00

Data impact:
Rollback:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f53f35ee9839'
down_revision: str | None = '7909a5b29a0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('messages_processed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id')
    )
    op.create_index('ix_heartbeat_last_seen', 'worker_heartbeats', ['last_seen_at'], unique=False)
    op.add_column('messages', sa.Column('provider_latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'provider_latency_ms')
    op.drop_index('ix_heartbeat_last_seen', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
